spring:
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/users?useSSL=false
    username: root
    password: root
    pool:
      initial-size: 100 
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
  application:
    name: user-service
logging:
  level:
    org.springframework: info
server:
  port: 8081
